apiVersion: v1
kind: Service
metadata:
  name: go-raft
spec:
  clusterIP: None
  selector:
    app: go-raft
  ports:
    - port: 34220
      name: peer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-raft
spec:
  selector:
    matchLabels:
      app: go-raft
  serviceName: go-raft
  replicas: 3
  template:
    metadata:
      name: go-raft
      labels:
        app: go-raft
    spec:
      containers:
        - name: go-raft
          image: go-raft-image
          imagePullPolicy: Always
          ports:
            - containerPort: 34220
              name: peer
          readinessProbe:
            grpc:
              port: 34220
          command:
            - bash
            - "-c"
            - |
              set -ex
              # get pod id
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              # run raft server
              ./go-raft server \
                  --me="go-raft-$ordinal.go-raft:34220" \
                  --members="go-raft-0.go-raft:34220, go-raft-1.go-raft:34220, go-raft-2.go-raft:34220" \
                  --tick=10 \
                  --eleMin=500 \
                  --eleMax=1000
          envFrom:
            - configMapRef:
                name: customer-env
                optional: true
          resources:
            requests:
              cpu: "300m"
              memory: "64Mi"
              ephemeral-storage: "128"
            limits:
              cpu: "100m"
              memory: "32Mi"
              ephemeral-storage: "64Mi"
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 12345
            runAsGroup: 23456


