apiVersion: v1
kind: Service
metadata:
  name: go-raft
spec:
  clusterIP: None
  selector:
    app: go-raft
  ports:
    - port: 34220
      name: peer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-raft
spec:
  selector:
    matchLabels:
      app: go-raft
  serviceName: go-raft
  replicas: 3
  template:
    metadata:
      name: go-raft
      labels:
        app: go-raft
    spec:
      containers:
        - name: go-raft
          image: go-raft-image
          ports:
            - containerPort: 34220
              name: peer
          command:
            - bash
            - "-c"
            - |
              set -ex
              # get pod id
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              # run raft server
              ./go-raft server --me="go-raft-$ordinal.go-raft:34220" --members="go-raft-0.go-raft:34220, go-raft-1.go-raft:34220, go-raft-2.go-raft:34220"
          envFrom:
            - configMapRef:
                name: customer-env
                optional: true
