apiVersion: v1
kind: Service
metadata:
  name: go-raft
spec:
  clusterIP: None
  selector:
    app: go-raft
  ports:
    - port: 34220
      name: peer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-raft
spec:
  selector:
    matchLabels:
      app: go-raft
  serviceName: go-raft
  replicas: 5
  template:
    metadata:
      name: go-raft
      labels:
        app: go-raft
    spec:
      containers:
        - name: go-raft
          image: ghcr.io/lenshood/go-raft:v0.1.0
          ports:
            - containerPort: 34220
              name: peer
          command:
            - ./go-raft
            - server
            - --members
            - go-raft-0.go-raft:34220, go-raft-1.go-raft:34220, go-raft-2.go-raft:34220

